/**
 * echoNotices.js — what Echo notices, and what she is allowed to say about it.
 *
 * Pure. No React, no timers, no DOM. The component decides WHEN to show a notice;
 * this module decides WHICH notices exist and how they are worded, so the rules are
 * assertable instead of buried in a render tree. Same split as `echoBehaviour.js`.
 *
 * ── The rule that shapes everything here ─────────────────────────────────────
 * A notice states a FACT drawn from the keeper's own logs. It never advises.
 *
 * The version this replaces said things like "your fish would appreciate one" and
 * "a quick test keeps everyone safe". That is husbandry advice, generated by a
 * hardcoded string table, attributed to Echo. Everywhere else this codebase is
 * careful about exactly that: Poseidon's system prompt forbids veterinary
 * diagnosis, and AI-drafted listing copy has a whitelisted-facts grounding
 * contract. Echo should not be the one place that gives unsourced care advice in a
 * friendly voice — and "6 days since a water change" is both safer AND more useful
 * than "time for a refresh?", because the keeper can check it.
 *
 * `noticeMentionsAdvice()` exists so that rule is enforced by a test rather than by
 * good intentions, since the tempting edit here is always to add one helpful line.
 *
 * ── Where the advice comes from instead ──────────────────────────────────────
 * Poseidon. Care notices carry a `seedPrompt`: tapping the bubble opens the chat
 * with that question already asked. He is the brain, he has the species RAG
 * context, he is bound by the anti-diagnosis prompt, and his writes go through
 * confirm-before-write. Echo notices; Poseidon explains. That is the division the
 * character spec asks for, and it also turns the bubble from a line that appears
 * and vanishes into something the keeper can act on.
 *
 * Celebratory notices have no `seedPrompt` on purpose — there is nothing to ask
 * about a streak, and inventing a question to satisfy a symmetry would be worse.
 */

import { getTierInfo, TIER_LADDER } from "../utils/xp";

const MS_PER_HOUR = 60 * 60 * 1000;
const MS_PER_DAY = 24 * MS_PER_HOUR;

/**
 * Thresholds at which something becomes worth mentioning. Named, because a bare
 * `>= 3` in a condition is unreviewable — and because these are the numbers a
 * keeper would argue with, so they should be easy to find and change.
 */
export const NOTICE_THRESHOLDS = Object.freeze({
  waterChangeDays: 3,
  feedingHours: 36,
  paramTestDays: 5,
  pointsFromTier: 200,
  newKeeperXp: 100,
});

/**
 * When a change between a tank's last two tests is worth a word. Ammonia and
 * nitrite have no threshold: any rise above zero is news.
 */
export const TREND_THRESHOLDS = Object.freeze({
  nitrateRisePpm: 10,
  nitrateHighPpm: 20,
  nitrateDropPpm: 10,
  phSwing: 0.5,
  tempSwingC: 2,
  // A change between two tests from last spring is not news.
  freshDays: 14,
});

/**
 * The water readings a trend can be about. Logs store fixed-point values
 * (×100 nitrogen, ×10 pH and temperature); `alt` is the older plain field,
 * stored in the same ×10 units (see components/logbook/latestReading.js).
 */
const TREND_PARAMS = Object.freeze([
  { key: "ammonia", field: "ammoniaPpmX100", div: 100 },
  { key: "nitrite", field: "nitritePpmX100", div: 100 },
  { key: "nitrate", field: "nitratePpmX100", div: 100 },
  { key: "ph", field: "phX10", alt: "ph", div: 10, positive: true },
  { key: "temp", field: "tempCelsiusX10", alt: "temp", div: 10, positive: true },
]);

/**
 * The last two logged values of each water parameter, per tank. Pure.
 *
 * A parameter needs two real readings to have a trend. A missing value is
 * skipped, never read as zero, so "not tested" can never look like "0 ppm".
 *
 * @param {object[]} tanks Dexie tank rows
 * @returns {Array<{tankId: any, tankName: string, param: string, last: number, prev: number, at: number}>}
 *   `at` is the newer log's timestamp in seconds.
 */
export function readingTrends(tanks = []) {
  const out = [];
  for (const tank of Array.isArray(tanks) ? tanks : []) {
    if (!tank || tank.active === false) continue;
    const logs = [...(Array.isArray(tank.logs) ? tank.logs : [])]
      .sort((a, b) => Number(b?.timestamp || 0) - Number(a?.timestamp || 0));
    for (const p of TREND_PARAMS) {
      const vals = [];
      for (const log of logs) {
        const raw = log?.[p.field] ?? (p.alt ? log?.[p.alt] : undefined);
        if (raw === null || raw === undefined || raw === "") continue;
        const n = Number(raw);
        if (!Number.isFinite(n) || n < 0 || (p.positive && n === 0)) continue;
        vals.push({ value: n / p.div, at: Number(log.timestamp) || 0 });
        if (vals.length === 2) break;
      }
      if (vals.length === 2) {
        out.push({
          tankId: tank.id,
          tankName: String(tank.name || "your tank").slice(0, 60),
          param: p.key,
          last: vals[0].value,
          prev: vals[1].value,
          at: vals[0].at,
        });
      }
    }
  }
  return out;
}

const ppm = (v) => (Number.isInteger(v) ? String(v) : v.toFixed(2).replace(/0+$/, "").replace(/\.$/, ""));
const oneDp = (v) => (Math.round(v * 10) / 10).toFixed(1);
const cToF = (c) => Math.round((c * 9) / 5 + 32);

/** Notices from the change between a tank's last two tests. */
function trendNotices(trends, now) {
  const out = [];
  for (const t of Array.isArray(trends) ? trends : []) {
    if (!t || !Number.isFinite(t.last) || !Number.isFinite(t.prev)) continue;
    if (!Number.isFinite(t.at) || now - t.at * 1000 > TREND_THRESHOLDS.freshDays * MS_PER_DAY) continue;
    const where = t.tankName || "your tank";
    const id = `trend-${t.param}-${t.tankId}`;

    if ((t.param === "ammonia" || t.param === "nitrite") && t.last > 0 && t.last > t.prev) {
      const Label = t.param === "ammonia" ? "Ammonia" : "Nitrite";
      out.push({
        id,
        priority: 5,
        icon: "⚠️",
        mood: "concerned",
        casual: `${Label} in ${where} read ${ppm(t.last)} ppm on the last test, up from ${ppm(t.prev)}.`,
        pro: `${Label.toUpperCase()} ${where}: ${ppm(t.prev)} → ${ppm(t.last)} ppm.`,
        seedPrompt: `${Label} in my tank "${where}" read ${ppm(t.last)} ppm on my last test, up from ${ppm(t.prev)}. What could cause that, and what should I check first?`,
      });
    } else if (t.param === "nitrate" && t.last - t.prev >= TREND_THRESHOLDS.nitrateRisePpm && t.last >= TREND_THRESHOLDS.nitrateHighPpm) {
      out.push({
        id,
        priority: 4,
        icon: "📈",
        mood: "alert",
        casual: `Nitrate in ${where} went from ${ppm(t.prev)} to ${ppm(t.last)} ppm between the last two tests.`,
        pro: `NITRATE ${where}: ${ppm(t.prev)} → ${ppm(t.last)} ppm.`,
        seedPrompt: `Nitrate in my tank "${where}" went from ${ppm(t.prev)} to ${ppm(t.last)} ppm between my last two tests. Why might it be climbing?`,
      });
    } else if (t.param === "nitrate" && t.prev - t.last >= TREND_THRESHOLDS.nitrateDropPpm) {
      out.push({
        id,
        priority: 1,
        icon: "📉",
        mood: "happy",
        casual: `Nitrate in ${where} dropped from ${ppm(t.prev)} to ${ppm(t.last)} ppm since the test before.`,
        pro: `NITRATE ${where}: ${ppm(t.prev)} → ${ppm(t.last)} ppm.`,
      });
    } else if (t.param === "ph" && Math.abs(t.last - t.prev) >= TREND_THRESHOLDS.phSwing) {
      out.push({
        id,
        priority: 3,
        icon: "🧪",
        mood: "alert",
        casual: `pH in ${where} moved from ${oneDp(t.prev)} to ${oneDp(t.last)} between the last two tests.`,
        pro: `PH ${where}: ${oneDp(t.prev)} → ${oneDp(t.last)}.`,
        seedPrompt: `pH in my tank "${where}" moved from ${oneDp(t.prev)} to ${oneDp(t.last)} between my last two tests. Is a change that size a problem, and what can cause it?`,
      });
    } else if (t.param === "temp" && Math.abs(t.last - t.prev) >= TREND_THRESHOLDS.tempSwingC) {
      out.push({
        id,
        priority: 3,
        icon: "🌡️",
        mood: "alert",
        casual: `Temperature in ${where} moved from ${cToF(t.prev)}°F (${oneDp(t.prev)}°C) to ${cToF(t.last)}°F (${oneDp(t.last)}°C) between the last two readings.`,
        pro: `TEMP ${where}: ${oneDp(t.prev)} → ${oneDp(t.last)}°C.`,
        seedPrompt: `The temperature in my tank "${where}" moved from ${oneDp(t.prev)}°C to ${oneDp(t.last)}°C between my last two readings. What could cause that?`,
      });
    }
  }
  return out;
}

/** Advice-shaped phrasing. If a notice matches any of these, it is not a fact. */
const ADVICE_PATTERNS = [
  /\byou should\b/i,
  /\byou ought\b/i,
  /\byou need to\b/i,
  /\bmake sure\b/i,
  /\bwe recommend\b/i,
  /\bwould appreciate\b/i,
  /\bdon'?t forget\b/i,
  /\btime for\b/i,
  /\bgood time\b/i,
  /\bkeeps? everyone safe\b/i,
  /\bshould be\b/i,
  /\btry logging\b/i,
];

/**
 * True when a string reads as advice rather than an observation.
 * Exported for the test that walks every notice this module can produce.
 */
export function noticeMentionsAdvice(text) {
  return ADVICE_PATTERNS.some((p) => p.test(String(text || "")));
}

const wholeDaysSince = (iso, now) => {
  const t = iso ? new Date(iso).getTime() : NaN;
  if (!Number.isFinite(t)) return null;
  return Math.floor((now - t) / MS_PER_DAY);
};

const wholeHoursSince = (iso, now) => {
  const t = iso ? new Date(iso).getTime() : NaN;
  if (!Number.isFinite(t)) return null;
  return Math.floor((now - t) / MS_PER_HOUR);
};

/**
 * Every notice currently true, highest priority first.
 *
 * Absent data produces NO notice rather than a guess: a keeper who has never
 * logged a water change should not be told it has been "NaN days", and silence is
 * the correct output when there is nothing to report.
 *
 * @param {{
 *   userState?: {totalXp?: number, streakDays?: number},
 *   tankData?: {lastWaterChange?: string|null, lastFeeding?: string|null,
 *               lastParams?: string|null, tankCount?: number,
 *               trends?: ReturnType<typeof readingTrends>},
 *   now?: number,
 * }} input
 * @returns {Array<{id: string, priority: number, icon: string, mood: string,
 *                  casual: string, pro: string, seedPrompt?: string}>}
 *   `mood` is Echo's face when she says it (echoBehaviour's mood list).
 */
export function buildNotices({ userState, tankData, now = Date.now() } = {}) {
  const { totalXp = 0, streakDays = 0 } = userState || {};
  const { lastWaterChange, lastFeeding, lastParams, tankCount = 0, trends = [] } = tankData || {};

  // ─── Changes between the last two tests (readingTrends) ─────────────────
  const notices = trendNotices(trends, now);

  // ─── Care: elapsed time since the keeper's own logs ─────────────────────
  const waterDays = wholeDaysSince(lastWaterChange, now);
  if (waterDays !== null && waterDays >= NOTICE_THRESHOLDS.waterChangeDays) {
    notices.push({
      id: "water-change",
      priority: waterDays >= 7 ? 4 : 3,
      icon: "💧",
      mood: "alert",
      casual: `It's been ${waterDays} days since a water change was logged.`,
      pro: `WATER CHANGE — last logged ${waterDays}d ago.`,
      seedPrompt: `My last logged water change was ${waterDays} days ago. What should I be looking at?`,
    });
  }

  const feedHours = wholeHoursSince(lastFeeding, now);
  if (feedHours !== null && feedHours >= NOTICE_THRESHOLDS.feedingHours) {
    notices.push({
      id: "feeding",
      priority: 2,
      icon: "🍽️",
      mood: "alert",
      casual: `No feeding logged in the last ${feedHours} hours.`,
      pro: `FEED — none logged in ${feedHours}h.`,
      seedPrompt: `I haven't logged a feeding in ${feedHours} hours. How often should my fish be fed?`,
    });
  }

  const paramDays = wholeDaysSince(lastParams, now);
  if (paramDays !== null && paramDays >= NOTICE_THRESHOLDS.paramTestDays) {
    notices.push({
      id: "params",
      priority: 2,
      icon: "🧪",
      mood: "alert",
      casual: `Water parameters were last tested ${paramDays} days ago.`,
      pro: `PARAMS — last test ${paramDays}d ago.`,
      seedPrompt: `My last water test was ${paramDays} days ago. Which parameters matter most for my tank?`,
    });
  }

  // ─── Progress: facts about their own XP ─────────────────────────────────
  const tierInfo = getTierInfo(totalXp);
  if (tierInfo?.nextLevelXp) {
    const remaining = tierInfo.nextLevelXp - totalXp;
    if (remaining > 0 && remaining <= NOTICE_THRESHOLDS.pointsFromTier) {
      const nextTier = TIER_LADDER.find((t) => t.min === tierInfo.nextLevelXp);
      notices.push({
        id: "near-tier",
        priority: 1,
        icon: "🌟",
        mood: "happy",
        casual: `${remaining} points from ${nextTier?.hobbyistLabel || "the next tier"}.`,
        pro: `${remaining} XP to ${nextTier?.breederLabel || "next tier"}.`,
      });
    }
  }

  // ─── Streak: a count, not a compliment on their fishkeeping ─────────────
  if (streakDays === 6) {
    notices.push({
      id: "streak-almost-week",
      priority: 3,
      icon: "🔥",
      mood: "happy",
      casual: "Six days logged in a row. One more makes a week.",
      pro: "STREAK 6d — one from a full week.",
    });
  } else if (streakDays >= 7 && streakDays % 7 === 0) {
    notices.push({
      id: "streak-week",
      priority: 1,
      icon: "✨",
      mood: "excited",
      casual: `${streakDays} days of logs in a row.`,
      pro: `STREAK ${streakDays}d.`,
    });
  } else if (streakDays >= 3) {
    notices.push({
      id: "streak-building",
      priority: 0,
      icon: "🔥",
      mood: "happy",
      casual: `${streakDays} days logged in a row.`,
      pro: `STREAK ${streakDays}d.`,
    });
  }

  // ─── A keeper with a tank and nothing logged yet ────────────────────────
  // Deliberately no instruction about what to log; the tap-through asks Poseidon,
  // who can answer it properly and in context.
  if (totalXp < NOTICE_THRESHOLDS.newKeeperXp && tankCount >= 1 && !lastWaterChange && !lastFeeding) {
    notices.push({
      id: "no-logs-yet",
      priority: 1,
      icon: "💡",
      mood: "calm",
      casual: "No care logs on record for your tanks yet.",
      pro: "NO CARE LOGS ON RECORD.",
      seedPrompt: "I'm just getting started. What's worth logging for a new tank?",
    });
  }

  return notices.sort((a, b) => b.priority - a.priority);
}

/**
 * Choose one notice to show.
 *
 * Random among equal-priority candidates so a keeper with two stale logs does not
 * see the same one every time, and `excludeId` prevents showing the same notice
 * twice running — which is what makes a repeating bubble feel like a broken loop.
 *
 * @param {ReturnType<typeof buildNotices>} notices
 * @param {{excludeId?: string|null, random?: () => number}} [options]
 */
export function pickNotice(notices, { excludeId = null, random = Math.random } = {}) {
  if (!Array.isArray(notices) || notices.length === 0) return null;

  // Only drop the repeat if something else is available; one true notice is better
  // than none.
  const eligible = notices.filter((n) => n.id !== excludeId);
  const pool = eligible.length > 0 ? eligible : notices;

  const top = pool[0].priority;
  const tied = pool.filter((n) => n.priority === top);
  return tied[Math.floor(random() * tied.length)] || tied[0];
}

/** The wording for a mode. Kept here so the component holds no copy. */
export function noticeText(notice, { pro = false } = {}) {
  if (!notice) return null;
  return pro ? notice.pro : notice.casual;
}
