-- Migration 008: Add media_alt_texts column to currents table
-- Stores AI-generated alt text for each uploaded photo (Poseidon Vision)
-- Array order matches media_urls[] — altTexts[0] corresponds to media_urls[0]

ALTER TABLE currents
ADD COLUMN IF NOT EXISTS media_alt_texts jsonb DEFAULT NULL;

COMMENT ON COLUMN currents.media_alt_texts IS 'AI-generated alt text array for media_urls. Each entry corresponds to the same index in media_urls. Generated by Poseidon via Gemini Vision.';
